title: Minju Yang
description: welcome to my channel
author: Minju Yang
avatar: /logo.jpg
email: alswn0558@gmail.com
theme: 
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
feed:
  excerpt_only: true

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus: True

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: Minju
  card: summary
logo: logo.jpg
social:
  name: Minju yang
  links:
    - https://twitter.com/ytm07185219
    - https://www.facebook.com/alswn0558/
    - https://github.com/alswn0558
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
